// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DatabaseEvent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DatabaseEvent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DatabaseEvent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DatabaseEvent_2eproto OPENTERAMESSAGES_EXPORT
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct OPENTERAMESSAGES_EXPORT TableStruct_DatabaseEvent_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
OPENTERAMESSAGES_EXPORT extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DatabaseEvent_2eproto;
namespace opentera {
namespace protobuf {
class DatabaseEvent;
struct DatabaseEventDefaultTypeInternal;
OPENTERAMESSAGES_EXPORT extern DatabaseEventDefaultTypeInternal _DatabaseEvent_default_instance_;
}  // namespace protobuf
}  // namespace opentera
PROTOBUF_NAMESPACE_OPEN
template<> OPENTERAMESSAGES_EXPORT ::opentera::protobuf::DatabaseEvent* Arena::CreateMaybeMessage<::opentera::protobuf::DatabaseEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace opentera {
namespace protobuf {

enum DatabaseEvent_EventType : int {
  DatabaseEvent_EventType_DB_UNKNOWN = 0,
  DatabaseEvent_EventType_DB_CREATE = 1,
  DatabaseEvent_EventType_DB_UPDATE = 2,
  DatabaseEvent_EventType_DB_DELETE = 3,
  DatabaseEvent_EventType_DatabaseEvent_EventType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  DatabaseEvent_EventType_DatabaseEvent_EventType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
OPENTERAMESSAGES_EXPORT bool DatabaseEvent_EventType_IsValid(int value);
constexpr DatabaseEvent_EventType DatabaseEvent_EventType_EventType_MIN = DatabaseEvent_EventType_DB_UNKNOWN;
constexpr DatabaseEvent_EventType DatabaseEvent_EventType_EventType_MAX = DatabaseEvent_EventType_DB_DELETE;
constexpr int DatabaseEvent_EventType_EventType_ARRAYSIZE = DatabaseEvent_EventType_EventType_MAX + 1;

OPENTERAMESSAGES_EXPORT const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DatabaseEvent_EventType_descriptor();
template<typename T>
inline const std::string& DatabaseEvent_EventType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DatabaseEvent_EventType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DatabaseEvent_EventType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DatabaseEvent_EventType_descriptor(), enum_t_value);
}
inline bool DatabaseEvent_EventType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DatabaseEvent_EventType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DatabaseEvent_EventType>(
    DatabaseEvent_EventType_descriptor(), name, value);
}
// ===================================================================

class OPENTERAMESSAGES_EXPORT DatabaseEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentera.protobuf.DatabaseEvent) */ {
 public:
  inline DatabaseEvent() : DatabaseEvent(nullptr) {}
  ~DatabaseEvent() override;
  explicit constexpr DatabaseEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DatabaseEvent(const DatabaseEvent& from);
  DatabaseEvent(DatabaseEvent&& from) noexcept
    : DatabaseEvent() {
    *this = ::std::move(from);
  }

  inline DatabaseEvent& operator=(const DatabaseEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline DatabaseEvent& operator=(DatabaseEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DatabaseEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const DatabaseEvent* internal_default_instance() {
    return reinterpret_cast<const DatabaseEvent*>(
               &_DatabaseEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DatabaseEvent& a, DatabaseEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(DatabaseEvent* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DatabaseEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DatabaseEvent* New() const final {
    return new DatabaseEvent();
  }

  DatabaseEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DatabaseEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DatabaseEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DatabaseEvent& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DatabaseEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentera.protobuf.DatabaseEvent";
  }
  protected:
  explicit DatabaseEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef DatabaseEvent_EventType EventType;
  static constexpr EventType DB_UNKNOWN =
    DatabaseEvent_EventType_DB_UNKNOWN;
  static constexpr EventType DB_CREATE =
    DatabaseEvent_EventType_DB_CREATE;
  static constexpr EventType DB_UPDATE =
    DatabaseEvent_EventType_DB_UPDATE;
  static constexpr EventType DB_DELETE =
    DatabaseEvent_EventType_DB_DELETE;
  static inline bool EventType_IsValid(int value) {
    return DatabaseEvent_EventType_IsValid(value);
  }
  static constexpr EventType EventType_MIN =
    DatabaseEvent_EventType_EventType_MIN;
  static constexpr EventType EventType_MAX =
    DatabaseEvent_EventType_EventType_MAX;
  static constexpr int EventType_ARRAYSIZE =
    DatabaseEvent_EventType_EventType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  EventType_descriptor() {
    return DatabaseEvent_EventType_descriptor();
  }
  template<typename T>
  static inline const std::string& EventType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, EventType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function EventType_Name.");
    return DatabaseEvent_EventType_Name(enum_t_value);
  }
  static inline bool EventType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      EventType* value) {
    return DatabaseEvent_EventType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kObjectTypeFieldNumber = 2,
    kObjectValueFieldNumber = 3,
    kTypeFieldNumber = 1,
  };
  // string object_type = 2;
  void clear_object_type();
  const std::string& object_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_object_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_object_type();
  PROTOBUF_MUST_USE_RESULT std::string* release_object_type();
  void set_allocated_object_type(std::string* object_type);
  private:
  const std::string& _internal_object_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_object_type(const std::string& value);
  std::string* _internal_mutable_object_type();
  public:

  // string object_value = 3;
  void clear_object_value();
  const std::string& object_value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_object_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_object_value();
  PROTOBUF_MUST_USE_RESULT std::string* release_object_value();
  void set_allocated_object_value(std::string* object_value);
  private:
  const std::string& _internal_object_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_object_value(const std::string& value);
  std::string* _internal_mutable_object_value();
  public:

  // .opentera.protobuf.DatabaseEvent.EventType type = 1;
  void clear_type();
  ::opentera::protobuf::DatabaseEvent_EventType type() const;
  void set_type(::opentera::protobuf::DatabaseEvent_EventType value);
  private:
  ::opentera::protobuf::DatabaseEvent_EventType _internal_type() const;
  void _internal_set_type(::opentera::protobuf::DatabaseEvent_EventType value);
  public:

  // @@protoc_insertion_point(class_scope:opentera.protobuf.DatabaseEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr object_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr object_value_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_DatabaseEvent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DatabaseEvent

// .opentera.protobuf.DatabaseEvent.EventType type = 1;
inline void DatabaseEvent::clear_type() {
  type_ = 0;
}
inline ::opentera::protobuf::DatabaseEvent_EventType DatabaseEvent::_internal_type() const {
  return static_cast< ::opentera::protobuf::DatabaseEvent_EventType >(type_);
}
inline ::opentera::protobuf::DatabaseEvent_EventType DatabaseEvent::type() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.DatabaseEvent.type)
  return _internal_type();
}
inline void DatabaseEvent::_internal_set_type(::opentera::protobuf::DatabaseEvent_EventType value) {
  
  type_ = value;
}
inline void DatabaseEvent::set_type(::opentera::protobuf::DatabaseEvent_EventType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:opentera.protobuf.DatabaseEvent.type)
}

// string object_type = 2;
inline void DatabaseEvent::clear_object_type() {
  object_type_.ClearToEmpty();
}
inline const std::string& DatabaseEvent::object_type() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.DatabaseEvent.object_type)
  return _internal_object_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DatabaseEvent::set_object_type(ArgT0&& arg0, ArgT... args) {
 
 object_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:opentera.protobuf.DatabaseEvent.object_type)
}
inline std::string* DatabaseEvent::mutable_object_type() {
  std::string* _s = _internal_mutable_object_type();
  // @@protoc_insertion_point(field_mutable:opentera.protobuf.DatabaseEvent.object_type)
  return _s;
}
inline const std::string& DatabaseEvent::_internal_object_type() const {
  return object_type_.Get();
}
inline void DatabaseEvent::_internal_set_object_type(const std::string& value) {
  
  object_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DatabaseEvent::_internal_mutable_object_type() {
  
  return object_type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DatabaseEvent::release_object_type() {
  // @@protoc_insertion_point(field_release:opentera.protobuf.DatabaseEvent.object_type)
  return object_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DatabaseEvent::set_allocated_object_type(std::string* object_type) {
  if (object_type != nullptr) {
    
  } else {
    
  }
  object_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), object_type,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:opentera.protobuf.DatabaseEvent.object_type)
}

// string object_value = 3;
inline void DatabaseEvent::clear_object_value() {
  object_value_.ClearToEmpty();
}
inline const std::string& DatabaseEvent::object_value() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.DatabaseEvent.object_value)
  return _internal_object_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DatabaseEvent::set_object_value(ArgT0&& arg0, ArgT... args) {
 
 object_value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:opentera.protobuf.DatabaseEvent.object_value)
}
inline std::string* DatabaseEvent::mutable_object_value() {
  std::string* _s = _internal_mutable_object_value();
  // @@protoc_insertion_point(field_mutable:opentera.protobuf.DatabaseEvent.object_value)
  return _s;
}
inline const std::string& DatabaseEvent::_internal_object_value() const {
  return object_value_.Get();
}
inline void DatabaseEvent::_internal_set_object_value(const std::string& value) {
  
  object_value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DatabaseEvent::_internal_mutable_object_value() {
  
  return object_value_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DatabaseEvent::release_object_value() {
  // @@protoc_insertion_point(field_release:opentera.protobuf.DatabaseEvent.object_value)
  return object_value_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DatabaseEvent::set_allocated_object_value(std::string* object_value) {
  if (object_value != nullptr) {
    
  } else {
    
  }
  object_value_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), object_value,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:opentera.protobuf.DatabaseEvent.object_value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace opentera

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::opentera::protobuf::DatabaseEvent_EventType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::opentera::protobuf::DatabaseEvent_EventType>() {
  return ::opentera::protobuf::DatabaseEvent_EventType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DatabaseEvent_2eproto
