// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceEvent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DeviceEvent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DeviceEvent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DeviceEvent_2eproto OPENTERAMESSAGES_EXPORT
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct OPENTERAMESSAGES_EXPORT TableStruct_DeviceEvent_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
OPENTERAMESSAGES_EXPORT extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DeviceEvent_2eproto;
namespace opentera {
namespace protobuf {
class DeviceEvent;
struct DeviceEventDefaultTypeInternal;
OPENTERAMESSAGES_EXPORT extern DeviceEventDefaultTypeInternal _DeviceEvent_default_instance_;
}  // namespace protobuf
}  // namespace opentera
PROTOBUF_NAMESPACE_OPEN
template<> OPENTERAMESSAGES_EXPORT ::opentera::protobuf::DeviceEvent* Arena::CreateMaybeMessage<::opentera::protobuf::DeviceEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace opentera {
namespace protobuf {

enum DeviceEvent_EventType : int {
  DeviceEvent_EventType_DEVICE_UNKNOWN = 0,
  DeviceEvent_EventType_DEVICE_CONNECTED = 1,
  DeviceEvent_EventType_DEVICE_DISCONNECTED = 2,
  DeviceEvent_EventType_DEVICE_DELETED = 3,
  DeviceEvent_EventType_DEVICE_ADDED = 4,
  DeviceEvent_EventType_DEVICE_JOINED_SESSION = 5,
  DeviceEvent_EventType_DEVICE_LEFT_SESSION = 6,
  DeviceEvent_EventType_DeviceEvent_EventType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  DeviceEvent_EventType_DeviceEvent_EventType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
OPENTERAMESSAGES_EXPORT bool DeviceEvent_EventType_IsValid(int value);
constexpr DeviceEvent_EventType DeviceEvent_EventType_EventType_MIN = DeviceEvent_EventType_DEVICE_UNKNOWN;
constexpr DeviceEvent_EventType DeviceEvent_EventType_EventType_MAX = DeviceEvent_EventType_DEVICE_LEFT_SESSION;
constexpr int DeviceEvent_EventType_EventType_ARRAYSIZE = DeviceEvent_EventType_EventType_MAX + 1;

OPENTERAMESSAGES_EXPORT const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DeviceEvent_EventType_descriptor();
template<typename T>
inline const std::string& DeviceEvent_EventType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DeviceEvent_EventType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DeviceEvent_EventType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DeviceEvent_EventType_descriptor(), enum_t_value);
}
inline bool DeviceEvent_EventType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DeviceEvent_EventType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DeviceEvent_EventType>(
    DeviceEvent_EventType_descriptor(), name, value);
}
// ===================================================================

class OPENTERAMESSAGES_EXPORT DeviceEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentera.protobuf.DeviceEvent) */ {
 public:
  inline DeviceEvent() : DeviceEvent(nullptr) {}
  ~DeviceEvent() override;
  explicit constexpr DeviceEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeviceEvent(const DeviceEvent& from);
  DeviceEvent(DeviceEvent&& from) noexcept
    : DeviceEvent() {
    *this = ::std::move(from);
  }

  inline DeviceEvent& operator=(const DeviceEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeviceEvent& operator=(DeviceEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DeviceEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeviceEvent* internal_default_instance() {
    return reinterpret_cast<const DeviceEvent*>(
               &_DeviceEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DeviceEvent& a, DeviceEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(DeviceEvent* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeviceEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DeviceEvent* New() const final {
    return new DeviceEvent();
  }

  DeviceEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DeviceEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DeviceEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DeviceEvent& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeviceEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentera.protobuf.DeviceEvent";
  }
  protected:
  explicit DeviceEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef DeviceEvent_EventType EventType;
  static constexpr EventType DEVICE_UNKNOWN =
    DeviceEvent_EventType_DEVICE_UNKNOWN;
  static constexpr EventType DEVICE_CONNECTED =
    DeviceEvent_EventType_DEVICE_CONNECTED;
  static constexpr EventType DEVICE_DISCONNECTED =
    DeviceEvent_EventType_DEVICE_DISCONNECTED;
  static constexpr EventType DEVICE_DELETED =
    DeviceEvent_EventType_DEVICE_DELETED;
  static constexpr EventType DEVICE_ADDED =
    DeviceEvent_EventType_DEVICE_ADDED;
  static constexpr EventType DEVICE_JOINED_SESSION =
    DeviceEvent_EventType_DEVICE_JOINED_SESSION;
  static constexpr EventType DEVICE_LEFT_SESSION =
    DeviceEvent_EventType_DEVICE_LEFT_SESSION;
  static inline bool EventType_IsValid(int value) {
    return DeviceEvent_EventType_IsValid(value);
  }
  static constexpr EventType EventType_MIN =
    DeviceEvent_EventType_EventType_MIN;
  static constexpr EventType EventType_MAX =
    DeviceEvent_EventType_EventType_MAX;
  static constexpr int EventType_ARRAYSIZE =
    DeviceEvent_EventType_EventType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  EventType_descriptor() {
    return DeviceEvent_EventType_descriptor();
  }
  template<typename T>
  static inline const std::string& EventType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, EventType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function EventType_Name.");
    return DeviceEvent_EventType_Name(enum_t_value);
  }
  static inline bool EventType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      EventType* value) {
    return DeviceEvent_EventType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kDeviceUuidFieldNumber = 1,
    kDeviceNameFieldNumber = 3,
    kTypeFieldNumber = 2,
  };
  // string device_uuid = 1;
  void clear_device_uuid();
  const std::string& device_uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_device_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_device_uuid();
  PROTOBUF_MUST_USE_RESULT std::string* release_device_uuid();
  void set_allocated_device_uuid(std::string* device_uuid);
  private:
  const std::string& _internal_device_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_device_uuid(const std::string& value);
  std::string* _internal_mutable_device_uuid();
  public:

  // string device_name = 3;
  void clear_device_name();
  const std::string& device_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_device_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_device_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_device_name();
  void set_allocated_device_name(std::string* device_name);
  private:
  const std::string& _internal_device_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_device_name(const std::string& value);
  std::string* _internal_mutable_device_name();
  public:

  // .opentera.protobuf.DeviceEvent.EventType type = 2;
  void clear_type();
  ::opentera::protobuf::DeviceEvent_EventType type() const;
  void set_type(::opentera::protobuf::DeviceEvent_EventType value);
  private:
  ::opentera::protobuf::DeviceEvent_EventType _internal_type() const;
  void _internal_set_type(::opentera::protobuf::DeviceEvent_EventType value);
  public:

  // @@protoc_insertion_point(class_scope:opentera.protobuf.DeviceEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr device_uuid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr device_name_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_DeviceEvent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DeviceEvent

// string device_uuid = 1;
inline void DeviceEvent::clear_device_uuid() {
  device_uuid_.ClearToEmpty();
}
inline const std::string& DeviceEvent::device_uuid() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.DeviceEvent.device_uuid)
  return _internal_device_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DeviceEvent::set_device_uuid(ArgT0&& arg0, ArgT... args) {
 
 device_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:opentera.protobuf.DeviceEvent.device_uuid)
}
inline std::string* DeviceEvent::mutable_device_uuid() {
  std::string* _s = _internal_mutable_device_uuid();
  // @@protoc_insertion_point(field_mutable:opentera.protobuf.DeviceEvent.device_uuid)
  return _s;
}
inline const std::string& DeviceEvent::_internal_device_uuid() const {
  return device_uuid_.Get();
}
inline void DeviceEvent::_internal_set_device_uuid(const std::string& value) {
  
  device_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DeviceEvent::_internal_mutable_device_uuid() {
  
  return device_uuid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DeviceEvent::release_device_uuid() {
  // @@protoc_insertion_point(field_release:opentera.protobuf.DeviceEvent.device_uuid)
  return device_uuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DeviceEvent::set_allocated_device_uuid(std::string* device_uuid) {
  if (device_uuid != nullptr) {
    
  } else {
    
  }
  device_uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), device_uuid,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:opentera.protobuf.DeviceEvent.device_uuid)
}

// .opentera.protobuf.DeviceEvent.EventType type = 2;
inline void DeviceEvent::clear_type() {
  type_ = 0;
}
inline ::opentera::protobuf::DeviceEvent_EventType DeviceEvent::_internal_type() const {
  return static_cast< ::opentera::protobuf::DeviceEvent_EventType >(type_);
}
inline ::opentera::protobuf::DeviceEvent_EventType DeviceEvent::type() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.DeviceEvent.type)
  return _internal_type();
}
inline void DeviceEvent::_internal_set_type(::opentera::protobuf::DeviceEvent_EventType value) {
  
  type_ = value;
}
inline void DeviceEvent::set_type(::opentera::protobuf::DeviceEvent_EventType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:opentera.protobuf.DeviceEvent.type)
}

// string device_name = 3;
inline void DeviceEvent::clear_device_name() {
  device_name_.ClearToEmpty();
}
inline const std::string& DeviceEvent::device_name() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.DeviceEvent.device_name)
  return _internal_device_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DeviceEvent::set_device_name(ArgT0&& arg0, ArgT... args) {
 
 device_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:opentera.protobuf.DeviceEvent.device_name)
}
inline std::string* DeviceEvent::mutable_device_name() {
  std::string* _s = _internal_mutable_device_name();
  // @@protoc_insertion_point(field_mutable:opentera.protobuf.DeviceEvent.device_name)
  return _s;
}
inline const std::string& DeviceEvent::_internal_device_name() const {
  return device_name_.Get();
}
inline void DeviceEvent::_internal_set_device_name(const std::string& value) {
  
  device_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* DeviceEvent::_internal_mutable_device_name() {
  
  return device_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* DeviceEvent::release_device_name() {
  // @@protoc_insertion_point(field_release:opentera.protobuf.DeviceEvent.device_name)
  return device_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void DeviceEvent::set_allocated_device_name(std::string* device_name) {
  if (device_name != nullptr) {
    
  } else {
    
  }
  device_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), device_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:opentera.protobuf.DeviceEvent.device_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace opentera

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::opentera::protobuf::DeviceEvent_EventType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::opentera::protobuf::DeviceEvent_EventType>() {
  return ::opentera::protobuf::DeviceEvent_EventType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DeviceEvent_2eproto
