// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JoinSessionEvent.proto

#include "JoinSessionEvent.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace opentera {
namespace protobuf {
constexpr JoinSessionEvent::JoinSessionEvent(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : session_participants_()
  , session_users_()
  , session_devices_()
  , session_url_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , session_creator_name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , session_uuid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , join_msg_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , session_parameters_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , service_uuid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct JoinSessionEventDefaultTypeInternal {
  constexpr JoinSessionEventDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~JoinSessionEventDefaultTypeInternal() {}
  union {
    JoinSessionEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT JoinSessionEventDefaultTypeInternal _JoinSessionEvent_default_instance_;
}  // namespace protobuf
}  // namespace opentera
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_JoinSessionEvent_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_JoinSessionEvent_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_JoinSessionEvent_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_JoinSessionEvent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionEvent, session_url_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionEvent, session_creator_name_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionEvent, session_uuid_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionEvent, session_participants_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionEvent, session_users_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionEvent, session_devices_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionEvent, join_msg_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionEvent, session_parameters_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionEvent, service_uuid_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::opentera::protobuf::JoinSessionEvent)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::opentera::protobuf::_JoinSessionEvent_default_instance_),
};

const char descriptor_table_protodef_JoinSessionEvent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026JoinSessionEvent.proto\022\021opentera.proto"
  "buf\"\355\001\n\020JoinSessionEvent\022\023\n\013session_url\030"
  "\001 \001(\t\022\034\n\024session_creator_name\030\002 \001(\t\022\024\n\014s"
  "ession_uuid\030\003 \001(\t\022\034\n\024session_participant"
  "s\030\004 \003(\t\022\025\n\rsession_users\030\005 \003(\t\022\027\n\017sessio"
  "n_devices\030\006 \003(\t\022\020\n\010join_msg\030\007 \001(\t\022\032\n\022ses"
  "sion_parameters\030\010 \001(\t\022\024\n\014service_uuid\030\t "
  "\001(\tb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_JoinSessionEvent_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_JoinSessionEvent_2eproto = {
  false, false, 291, descriptor_table_protodef_JoinSessionEvent_2eproto, "JoinSessionEvent.proto", 
  &descriptor_table_JoinSessionEvent_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_JoinSessionEvent_2eproto::offsets,
  file_level_metadata_JoinSessionEvent_2eproto, file_level_enum_descriptors_JoinSessionEvent_2eproto, file_level_service_descriptors_JoinSessionEvent_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_JoinSessionEvent_2eproto_getter() {
  return &descriptor_table_JoinSessionEvent_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_JoinSessionEvent_2eproto(&descriptor_table_JoinSessionEvent_2eproto);
namespace opentera {
namespace protobuf {

// ===================================================================

class JoinSessionEvent::_Internal {
 public:
};

JoinSessionEvent::JoinSessionEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  session_participants_(arena),
  session_users_(arena),
  session_devices_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:opentera.protobuf.JoinSessionEvent)
}
JoinSessionEvent::JoinSessionEvent(const JoinSessionEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      session_participants_(from.session_participants_),
      session_users_(from.session_users_),
      session_devices_(from.session_devices_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  session_url_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_session_url().empty()) {
    session_url_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_session_url(), 
      GetArenaForAllocation());
  }
  session_creator_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_session_creator_name().empty()) {
    session_creator_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_session_creator_name(), 
      GetArenaForAllocation());
  }
  session_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_session_uuid().empty()) {
    session_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_session_uuid(), 
      GetArenaForAllocation());
  }
  join_msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_join_msg().empty()) {
    join_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_join_msg(), 
      GetArenaForAllocation());
  }
  session_parameters_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_session_parameters().empty()) {
    session_parameters_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_session_parameters(), 
      GetArenaForAllocation());
  }
  service_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_service_uuid().empty()) {
    service_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_service_uuid(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:opentera.protobuf.JoinSessionEvent)
}

inline void JoinSessionEvent::SharedCtor() {
session_url_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
session_creator_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
session_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
join_msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
session_parameters_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
service_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

JoinSessionEvent::~JoinSessionEvent() {
  // @@protoc_insertion_point(destructor:opentera.protobuf.JoinSessionEvent)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void JoinSessionEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  session_url_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  session_creator_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  session_uuid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  join_msg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  session_parameters_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  service_uuid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void JoinSessionEvent::ArenaDtor(void* object) {
  JoinSessionEvent* _this = reinterpret_cast< JoinSessionEvent* >(object);
  (void)_this;
}
void JoinSessionEvent::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void JoinSessionEvent::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void JoinSessionEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:opentera.protobuf.JoinSessionEvent)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  session_participants_.Clear();
  session_users_.Clear();
  session_devices_.Clear();
  session_url_.ClearToEmpty();
  session_creator_name_.ClearToEmpty();
  session_uuid_.ClearToEmpty();
  join_msg_.ClearToEmpty();
  session_parameters_.ClearToEmpty();
  service_uuid_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* JoinSessionEvent::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string session_url = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_session_url();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionEvent.session_url"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string session_creator_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_session_creator_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionEvent.session_creator_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string session_uuid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_session_uuid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionEvent.session_uuid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string session_participants = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_session_participants();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionEvent.session_participants"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated string session_users = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_session_users();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionEvent.session_users"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated string session_devices = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_session_devices();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionEvent.session_devices"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      // string join_msg = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          auto str = _internal_mutable_join_msg();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionEvent.join_msg"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string session_parameters = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          auto str = _internal_mutable_session_parameters();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionEvent.session_parameters"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string service_uuid = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          auto str = _internal_mutable_service_uuid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionEvent.service_uuid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* JoinSessionEvent::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:opentera.protobuf.JoinSessionEvent)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string session_url = 1;
  if (!this->_internal_session_url().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_url().data(), static_cast<int>(this->_internal_session_url().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionEvent.session_url");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_session_url(), target);
  }

  // string session_creator_name = 2;
  if (!this->_internal_session_creator_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_creator_name().data(), static_cast<int>(this->_internal_session_creator_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionEvent.session_creator_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_session_creator_name(), target);
  }

  // string session_uuid = 3;
  if (!this->_internal_session_uuid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_uuid().data(), static_cast<int>(this->_internal_session_uuid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionEvent.session_uuid");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_session_uuid(), target);
  }

  // repeated string session_participants = 4;
  for (int i = 0, n = this->_internal_session_participants_size(); i < n; i++) {
    const auto& s = this->_internal_session_participants(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionEvent.session_participants");
    target = stream->WriteString(4, s, target);
  }

  // repeated string session_users = 5;
  for (int i = 0, n = this->_internal_session_users_size(); i < n; i++) {
    const auto& s = this->_internal_session_users(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionEvent.session_users");
    target = stream->WriteString(5, s, target);
  }

  // repeated string session_devices = 6;
  for (int i = 0, n = this->_internal_session_devices_size(); i < n; i++) {
    const auto& s = this->_internal_session_devices(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionEvent.session_devices");
    target = stream->WriteString(6, s, target);
  }

  // string join_msg = 7;
  if (!this->_internal_join_msg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_join_msg().data(), static_cast<int>(this->_internal_join_msg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionEvent.join_msg");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_join_msg(), target);
  }

  // string session_parameters = 8;
  if (!this->_internal_session_parameters().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_parameters().data(), static_cast<int>(this->_internal_session_parameters().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionEvent.session_parameters");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_session_parameters(), target);
  }

  // string service_uuid = 9;
  if (!this->_internal_service_uuid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_service_uuid().data(), static_cast<int>(this->_internal_service_uuid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionEvent.service_uuid");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_service_uuid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opentera.protobuf.JoinSessionEvent)
  return target;
}

size_t JoinSessionEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opentera.protobuf.JoinSessionEvent)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string session_participants = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(session_participants_.size());
  for (int i = 0, n = session_participants_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      session_participants_.Get(i));
  }

  // repeated string session_users = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(session_users_.size());
  for (int i = 0, n = session_users_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      session_users_.Get(i));
  }

  // repeated string session_devices = 6;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(session_devices_.size());
  for (int i = 0, n = session_devices_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      session_devices_.Get(i));
  }

  // string session_url = 1;
  if (!this->_internal_session_url().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_url());
  }

  // string session_creator_name = 2;
  if (!this->_internal_session_creator_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_creator_name());
  }

  // string session_uuid = 3;
  if (!this->_internal_session_uuid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_uuid());
  }

  // string join_msg = 7;
  if (!this->_internal_join_msg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_join_msg());
  }

  // string session_parameters = 8;
  if (!this->_internal_session_parameters().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_parameters());
  }

  // string service_uuid = 9;
  if (!this->_internal_service_uuid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_service_uuid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData JoinSessionEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    JoinSessionEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*JoinSessionEvent::GetClassData() const { return &_class_data_; }

void JoinSessionEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<JoinSessionEvent *>(to)->MergeFrom(
      static_cast<const JoinSessionEvent &>(from));
}


void JoinSessionEvent::MergeFrom(const JoinSessionEvent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opentera.protobuf.JoinSessionEvent)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  session_participants_.MergeFrom(from.session_participants_);
  session_users_.MergeFrom(from.session_users_);
  session_devices_.MergeFrom(from.session_devices_);
  if (!from._internal_session_url().empty()) {
    _internal_set_session_url(from._internal_session_url());
  }
  if (!from._internal_session_creator_name().empty()) {
    _internal_set_session_creator_name(from._internal_session_creator_name());
  }
  if (!from._internal_session_uuid().empty()) {
    _internal_set_session_uuid(from._internal_session_uuid());
  }
  if (!from._internal_join_msg().empty()) {
    _internal_set_join_msg(from._internal_join_msg());
  }
  if (!from._internal_session_parameters().empty()) {
    _internal_set_session_parameters(from._internal_session_parameters());
  }
  if (!from._internal_service_uuid().empty()) {
    _internal_set_service_uuid(from._internal_service_uuid());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void JoinSessionEvent::CopyFrom(const JoinSessionEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opentera.protobuf.JoinSessionEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JoinSessionEvent::IsInitialized() const {
  return true;
}

void JoinSessionEvent::InternalSwap(JoinSessionEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  session_participants_.InternalSwap(&other->session_participants_);
  session_users_.InternalSwap(&other->session_users_);
  session_devices_.InternalSwap(&other->session_devices_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &session_url_, GetArenaForAllocation(),
      &other->session_url_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &session_creator_name_, GetArenaForAllocation(),
      &other->session_creator_name_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &session_uuid_, GetArenaForAllocation(),
      &other->session_uuid_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &join_msg_, GetArenaForAllocation(),
      &other->join_msg_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &session_parameters_, GetArenaForAllocation(),
      &other->session_parameters_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &service_uuid_, GetArenaForAllocation(),
      &other->service_uuid_, other->GetArenaForAllocation()
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata JoinSessionEvent::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_JoinSessionEvent_2eproto_getter, &descriptor_table_JoinSessionEvent_2eproto_once,
      file_level_metadata_JoinSessionEvent_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace opentera
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::opentera::protobuf::JoinSessionEvent* Arena::CreateMaybeMessage< ::opentera::protobuf::JoinSessionEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::opentera::protobuf::JoinSessionEvent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
