// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JoinSessionReplyEvent.proto

#include "JoinSessionReplyEvent.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace opentera {
namespace protobuf {
constexpr JoinSessionReplyEvent::JoinSessionReplyEvent(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : session_uuid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , user_uuid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , participant_uuid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , device_uuid_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , reply_msg_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , join_reply_(0)
{}
struct JoinSessionReplyEventDefaultTypeInternal {
  constexpr JoinSessionReplyEventDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~JoinSessionReplyEventDefaultTypeInternal() {}
  union {
    JoinSessionReplyEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT JoinSessionReplyEventDefaultTypeInternal _JoinSessionReplyEvent_default_instance_;
}  // namespace protobuf
}  // namespace opentera
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_JoinSessionReplyEvent_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_JoinSessionReplyEvent_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_JoinSessionReplyEvent_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_JoinSessionReplyEvent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionReplyEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionReplyEvent, session_uuid_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionReplyEvent, user_uuid_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionReplyEvent, participant_uuid_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionReplyEvent, device_uuid_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionReplyEvent, join_reply_),
  PROTOBUF_FIELD_OFFSET(::opentera::protobuf::JoinSessionReplyEvent, reply_msg_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::opentera::protobuf::JoinSessionReplyEvent)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::opentera::protobuf::_JoinSessionReplyEvent_default_instance_),
};

const char descriptor_table_protodef_JoinSessionReplyEvent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033JoinSessionReplyEvent.proto\022\021opentera."
  "protobuf\"\263\002\n\025JoinSessionReplyEvent\022\024\n\014se"
  "ssion_uuid\030\001 \001(\t\022\021\n\tuser_uuid\030\002 \001(\t\022\030\n\020p"
  "articipant_uuid\030\003 \001(\t\022\023\n\013device_uuid\030\004 \001"
  "(\t\022F\n\njoin_reply\030\005 \001(\01622.opentera.protob"
  "uf.JoinSessionReplyEvent.ReplyType\022\021\n\tre"
  "ply_msg\030\006 \001(\t\"g\n\tReplyType\022\021\n\rREPLY_UNKN"
  "OWN\020\000\022\022\n\016REPLY_ACCEPTED\020\001\022\020\n\014REPLY_DENIE"
  "D\020\002\022\016\n\nREPLY_BUSY\020\003\022\021\n\rREPLY_TIMEOUT\020\004b\006"
  "proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_JoinSessionReplyEvent_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_JoinSessionReplyEvent_2eproto = {
  false, false, 366, descriptor_table_protodef_JoinSessionReplyEvent_2eproto, "JoinSessionReplyEvent.proto", 
  &descriptor_table_JoinSessionReplyEvent_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_JoinSessionReplyEvent_2eproto::offsets,
  file_level_metadata_JoinSessionReplyEvent_2eproto, file_level_enum_descriptors_JoinSessionReplyEvent_2eproto, file_level_service_descriptors_JoinSessionReplyEvent_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_JoinSessionReplyEvent_2eproto_getter() {
  return &descriptor_table_JoinSessionReplyEvent_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_JoinSessionReplyEvent_2eproto(&descriptor_table_JoinSessionReplyEvent_2eproto);
namespace opentera {
namespace protobuf {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* JoinSessionReplyEvent_ReplyType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_JoinSessionReplyEvent_2eproto);
  return file_level_enum_descriptors_JoinSessionReplyEvent_2eproto[0];
}
bool JoinSessionReplyEvent_ReplyType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr JoinSessionReplyEvent_ReplyType JoinSessionReplyEvent::REPLY_UNKNOWN;
constexpr JoinSessionReplyEvent_ReplyType JoinSessionReplyEvent::REPLY_ACCEPTED;
constexpr JoinSessionReplyEvent_ReplyType JoinSessionReplyEvent::REPLY_DENIED;
constexpr JoinSessionReplyEvent_ReplyType JoinSessionReplyEvent::REPLY_BUSY;
constexpr JoinSessionReplyEvent_ReplyType JoinSessionReplyEvent::REPLY_TIMEOUT;
constexpr JoinSessionReplyEvent_ReplyType JoinSessionReplyEvent::ReplyType_MIN;
constexpr JoinSessionReplyEvent_ReplyType JoinSessionReplyEvent::ReplyType_MAX;
constexpr int JoinSessionReplyEvent::ReplyType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class JoinSessionReplyEvent::_Internal {
 public:
};

JoinSessionReplyEvent::JoinSessionReplyEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:opentera.protobuf.JoinSessionReplyEvent)
}
JoinSessionReplyEvent::JoinSessionReplyEvent(const JoinSessionReplyEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  session_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_session_uuid().empty()) {
    session_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_session_uuid(), 
      GetArenaForAllocation());
  }
  user_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_user_uuid().empty()) {
    user_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_user_uuid(), 
      GetArenaForAllocation());
  }
  participant_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_participant_uuid().empty()) {
    participant_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_participant_uuid(), 
      GetArenaForAllocation());
  }
  device_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_device_uuid().empty()) {
    device_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_device_uuid(), 
      GetArenaForAllocation());
  }
  reply_msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_reply_msg().empty()) {
    reply_msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_reply_msg(), 
      GetArenaForAllocation());
  }
  join_reply_ = from.join_reply_;
  // @@protoc_insertion_point(copy_constructor:opentera.protobuf.JoinSessionReplyEvent)
}

inline void JoinSessionReplyEvent::SharedCtor() {
session_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
user_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
participant_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
device_uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
reply_msg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
join_reply_ = 0;
}

JoinSessionReplyEvent::~JoinSessionReplyEvent() {
  // @@protoc_insertion_point(destructor:opentera.protobuf.JoinSessionReplyEvent)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void JoinSessionReplyEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  session_uuid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  user_uuid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  participant_uuid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  device_uuid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  reply_msg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void JoinSessionReplyEvent::ArenaDtor(void* object) {
  JoinSessionReplyEvent* _this = reinterpret_cast< JoinSessionReplyEvent* >(object);
  (void)_this;
}
void JoinSessionReplyEvent::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void JoinSessionReplyEvent::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void JoinSessionReplyEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:opentera.protobuf.JoinSessionReplyEvent)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  session_uuid_.ClearToEmpty();
  user_uuid_.ClearToEmpty();
  participant_uuid_.ClearToEmpty();
  device_uuid_.ClearToEmpty();
  reply_msg_.ClearToEmpty();
  join_reply_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* JoinSessionReplyEvent::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string session_uuid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_session_uuid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionReplyEvent.session_uuid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string user_uuid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_user_uuid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionReplyEvent.user_uuid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string participant_uuid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_participant_uuid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionReplyEvent.participant_uuid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string device_uuid = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_device_uuid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionReplyEvent.device_uuid"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .opentera.protobuf.JoinSessionReplyEvent.ReplyType join_reply = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_join_reply(static_cast<::opentera::protobuf::JoinSessionReplyEvent_ReplyType>(val));
        } else goto handle_unusual;
        continue;
      // string reply_msg = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_reply_msg();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "opentera.protobuf.JoinSessionReplyEvent.reply_msg"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* JoinSessionReplyEvent::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:opentera.protobuf.JoinSessionReplyEvent)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string session_uuid = 1;
  if (!this->_internal_session_uuid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_uuid().data(), static_cast<int>(this->_internal_session_uuid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionReplyEvent.session_uuid");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_session_uuid(), target);
  }

  // string user_uuid = 2;
  if (!this->_internal_user_uuid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_user_uuid().data(), static_cast<int>(this->_internal_user_uuid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionReplyEvent.user_uuid");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_user_uuid(), target);
  }

  // string participant_uuid = 3;
  if (!this->_internal_participant_uuid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_participant_uuid().data(), static_cast<int>(this->_internal_participant_uuid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionReplyEvent.participant_uuid");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_participant_uuid(), target);
  }

  // string device_uuid = 4;
  if (!this->_internal_device_uuid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_device_uuid().data(), static_cast<int>(this->_internal_device_uuid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionReplyEvent.device_uuid");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_device_uuid(), target);
  }

  // .opentera.protobuf.JoinSessionReplyEvent.ReplyType join_reply = 5;
  if (this->_internal_join_reply() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      5, this->_internal_join_reply(), target);
  }

  // string reply_msg = 6;
  if (!this->_internal_reply_msg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reply_msg().data(), static_cast<int>(this->_internal_reply_msg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "opentera.protobuf.JoinSessionReplyEvent.reply_msg");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_reply_msg(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opentera.protobuf.JoinSessionReplyEvent)
  return target;
}

size_t JoinSessionReplyEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opentera.protobuf.JoinSessionReplyEvent)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string session_uuid = 1;
  if (!this->_internal_session_uuid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_uuid());
  }

  // string user_uuid = 2;
  if (!this->_internal_user_uuid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_user_uuid());
  }

  // string participant_uuid = 3;
  if (!this->_internal_participant_uuid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_participant_uuid());
  }

  // string device_uuid = 4;
  if (!this->_internal_device_uuid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_device_uuid());
  }

  // string reply_msg = 6;
  if (!this->_internal_reply_msg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reply_msg());
  }

  // .opentera.protobuf.JoinSessionReplyEvent.ReplyType join_reply = 5;
  if (this->_internal_join_reply() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_join_reply());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData JoinSessionReplyEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    JoinSessionReplyEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*JoinSessionReplyEvent::GetClassData() const { return &_class_data_; }

void JoinSessionReplyEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<JoinSessionReplyEvent *>(to)->MergeFrom(
      static_cast<const JoinSessionReplyEvent &>(from));
}


void JoinSessionReplyEvent::MergeFrom(const JoinSessionReplyEvent& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:opentera.protobuf.JoinSessionReplyEvent)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_session_uuid().empty()) {
    _internal_set_session_uuid(from._internal_session_uuid());
  }
  if (!from._internal_user_uuid().empty()) {
    _internal_set_user_uuid(from._internal_user_uuid());
  }
  if (!from._internal_participant_uuid().empty()) {
    _internal_set_participant_uuid(from._internal_participant_uuid());
  }
  if (!from._internal_device_uuid().empty()) {
    _internal_set_device_uuid(from._internal_device_uuid());
  }
  if (!from._internal_reply_msg().empty()) {
    _internal_set_reply_msg(from._internal_reply_msg());
  }
  if (from._internal_join_reply() != 0) {
    _internal_set_join_reply(from._internal_join_reply());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void JoinSessionReplyEvent::CopyFrom(const JoinSessionReplyEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opentera.protobuf.JoinSessionReplyEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JoinSessionReplyEvent::IsInitialized() const {
  return true;
}

void JoinSessionReplyEvent::InternalSwap(JoinSessionReplyEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &session_uuid_, GetArenaForAllocation(),
      &other->session_uuid_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &user_uuid_, GetArenaForAllocation(),
      &other->user_uuid_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &participant_uuid_, GetArenaForAllocation(),
      &other->participant_uuid_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &device_uuid_, GetArenaForAllocation(),
      &other->device_uuid_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &reply_msg_, GetArenaForAllocation(),
      &other->reply_msg_, other->GetArenaForAllocation()
  );
  swap(join_reply_, other->join_reply_);
}

::PROTOBUF_NAMESPACE_ID::Metadata JoinSessionReplyEvent::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_JoinSessionReplyEvent_2eproto_getter, &descriptor_table_JoinSessionReplyEvent_2eproto_once,
      file_level_metadata_JoinSessionReplyEvent_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace opentera
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::opentera::protobuf::JoinSessionReplyEvent* Arena::CreateMaybeMessage< ::opentera::protobuf::JoinSessionReplyEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::opentera::protobuf::JoinSessionReplyEvent >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
