// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ParticipantEvent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ParticipantEvent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ParticipantEvent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ParticipantEvent_2eproto OPENTERAMESSAGES_EXPORT
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct OPENTERAMESSAGES_EXPORT TableStruct_ParticipantEvent_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
OPENTERAMESSAGES_EXPORT extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ParticipantEvent_2eproto;
namespace opentera {
namespace protobuf {
class ParticipantEvent;
struct ParticipantEventDefaultTypeInternal;
OPENTERAMESSAGES_EXPORT extern ParticipantEventDefaultTypeInternal _ParticipantEvent_default_instance_;
}  // namespace protobuf
}  // namespace opentera
PROTOBUF_NAMESPACE_OPEN
template<> OPENTERAMESSAGES_EXPORT ::opentera::protobuf::ParticipantEvent* Arena::CreateMaybeMessage<::opentera::protobuf::ParticipantEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace opentera {
namespace protobuf {

enum ParticipantEvent_EventType : int {
  ParticipantEvent_EventType_PARTICIPANT_UNKNOWN = 0,
  ParticipantEvent_EventType_PARTICIPANT_CONNECTED = 1,
  ParticipantEvent_EventType_PARTICIPANT_DISCONNECTED = 2,
  ParticipantEvent_EventType_PARTICIPANT_DELETED = 3,
  ParticipantEvent_EventType_PARTICIPANT_ADDED = 4,
  ParticipantEvent_EventType_PARTICIPANT_JOINED_SESSION = 5,
  ParticipantEvent_EventType_PARTICIPANT_LEFT_SESSION = 6,
  ParticipantEvent_EventType_ParticipantEvent_EventType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ParticipantEvent_EventType_ParticipantEvent_EventType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
OPENTERAMESSAGES_EXPORT bool ParticipantEvent_EventType_IsValid(int value);
constexpr ParticipantEvent_EventType ParticipantEvent_EventType_EventType_MIN = ParticipantEvent_EventType_PARTICIPANT_UNKNOWN;
constexpr ParticipantEvent_EventType ParticipantEvent_EventType_EventType_MAX = ParticipantEvent_EventType_PARTICIPANT_LEFT_SESSION;
constexpr int ParticipantEvent_EventType_EventType_ARRAYSIZE = ParticipantEvent_EventType_EventType_MAX + 1;

OPENTERAMESSAGES_EXPORT const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ParticipantEvent_EventType_descriptor();
template<typename T>
inline const std::string& ParticipantEvent_EventType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ParticipantEvent_EventType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ParticipantEvent_EventType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ParticipantEvent_EventType_descriptor(), enum_t_value);
}
inline bool ParticipantEvent_EventType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ParticipantEvent_EventType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ParticipantEvent_EventType>(
    ParticipantEvent_EventType_descriptor(), name, value);
}
// ===================================================================

class OPENTERAMESSAGES_EXPORT ParticipantEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentera.protobuf.ParticipantEvent) */ {
 public:
  inline ParticipantEvent() : ParticipantEvent(nullptr) {}
  ~ParticipantEvent() override;
  explicit constexpr ParticipantEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ParticipantEvent(const ParticipantEvent& from);
  ParticipantEvent(ParticipantEvent&& from) noexcept
    : ParticipantEvent() {
    *this = ::std::move(from);
  }

  inline ParticipantEvent& operator=(const ParticipantEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParticipantEvent& operator=(ParticipantEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ParticipantEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const ParticipantEvent* internal_default_instance() {
    return reinterpret_cast<const ParticipantEvent*>(
               &_ParticipantEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ParticipantEvent& a, ParticipantEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(ParticipantEvent* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParticipantEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ParticipantEvent* New() const final {
    return new ParticipantEvent();
  }

  ParticipantEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ParticipantEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ParticipantEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ParticipantEvent& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ParticipantEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentera.protobuf.ParticipantEvent";
  }
  protected:
  explicit ParticipantEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ParticipantEvent_EventType EventType;
  static constexpr EventType PARTICIPANT_UNKNOWN =
    ParticipantEvent_EventType_PARTICIPANT_UNKNOWN;
  static constexpr EventType PARTICIPANT_CONNECTED =
    ParticipantEvent_EventType_PARTICIPANT_CONNECTED;
  static constexpr EventType PARTICIPANT_DISCONNECTED =
    ParticipantEvent_EventType_PARTICIPANT_DISCONNECTED;
  static constexpr EventType PARTICIPANT_DELETED =
    ParticipantEvent_EventType_PARTICIPANT_DELETED;
  static constexpr EventType PARTICIPANT_ADDED =
    ParticipantEvent_EventType_PARTICIPANT_ADDED;
  static constexpr EventType PARTICIPANT_JOINED_SESSION =
    ParticipantEvent_EventType_PARTICIPANT_JOINED_SESSION;
  static constexpr EventType PARTICIPANT_LEFT_SESSION =
    ParticipantEvent_EventType_PARTICIPANT_LEFT_SESSION;
  static inline bool EventType_IsValid(int value) {
    return ParticipantEvent_EventType_IsValid(value);
  }
  static constexpr EventType EventType_MIN =
    ParticipantEvent_EventType_EventType_MIN;
  static constexpr EventType EventType_MAX =
    ParticipantEvent_EventType_EventType_MAX;
  static constexpr int EventType_ARRAYSIZE =
    ParticipantEvent_EventType_EventType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  EventType_descriptor() {
    return ParticipantEvent_EventType_descriptor();
  }
  template<typename T>
  static inline const std::string& EventType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, EventType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function EventType_Name.");
    return ParticipantEvent_EventType_Name(enum_t_value);
  }
  static inline bool EventType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      EventType* value) {
    return ParticipantEvent_EventType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kParticipantUuidFieldNumber = 1,
    kParticipantNameFieldNumber = 3,
    kParticipantProjectNameFieldNumber = 4,
    kParticipantSiteNameFieldNumber = 5,
    kTypeFieldNumber = 2,
  };
  // string participant_uuid = 1;
  void clear_participant_uuid();
  const std::string& participant_uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_participant_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_participant_uuid();
  PROTOBUF_MUST_USE_RESULT std::string* release_participant_uuid();
  void set_allocated_participant_uuid(std::string* participant_uuid);
  private:
  const std::string& _internal_participant_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_participant_uuid(const std::string& value);
  std::string* _internal_mutable_participant_uuid();
  public:

  // string participant_name = 3;
  void clear_participant_name();
  const std::string& participant_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_participant_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_participant_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_participant_name();
  void set_allocated_participant_name(std::string* participant_name);
  private:
  const std::string& _internal_participant_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_participant_name(const std::string& value);
  std::string* _internal_mutable_participant_name();
  public:

  // string participant_project_name = 4;
  void clear_participant_project_name();
  const std::string& participant_project_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_participant_project_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_participant_project_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_participant_project_name();
  void set_allocated_participant_project_name(std::string* participant_project_name);
  private:
  const std::string& _internal_participant_project_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_participant_project_name(const std::string& value);
  std::string* _internal_mutable_participant_project_name();
  public:

  // string participant_site_name = 5;
  void clear_participant_site_name();
  const std::string& participant_site_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_participant_site_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_participant_site_name();
  PROTOBUF_MUST_USE_RESULT std::string* release_participant_site_name();
  void set_allocated_participant_site_name(std::string* participant_site_name);
  private:
  const std::string& _internal_participant_site_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_participant_site_name(const std::string& value);
  std::string* _internal_mutable_participant_site_name();
  public:

  // .opentera.protobuf.ParticipantEvent.EventType type = 2;
  void clear_type();
  ::opentera::protobuf::ParticipantEvent_EventType type() const;
  void set_type(::opentera::protobuf::ParticipantEvent_EventType value);
  private:
  ::opentera::protobuf::ParticipantEvent_EventType _internal_type() const;
  void _internal_set_type(::opentera::protobuf::ParticipantEvent_EventType value);
  public:

  // @@protoc_insertion_point(class_scope:opentera.protobuf.ParticipantEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr participant_uuid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr participant_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr participant_project_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr participant_site_name_;
  int type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ParticipantEvent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ParticipantEvent

// string participant_uuid = 1;
inline void ParticipantEvent::clear_participant_uuid() {
  participant_uuid_.ClearToEmpty();
}
inline const std::string& ParticipantEvent::participant_uuid() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.ParticipantEvent.participant_uuid)
  return _internal_participant_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ParticipantEvent::set_participant_uuid(ArgT0&& arg0, ArgT... args) {
 
 participant_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:opentera.protobuf.ParticipantEvent.participant_uuid)
}
inline std::string* ParticipantEvent::mutable_participant_uuid() {
  std::string* _s = _internal_mutable_participant_uuid();
  // @@protoc_insertion_point(field_mutable:opentera.protobuf.ParticipantEvent.participant_uuid)
  return _s;
}
inline const std::string& ParticipantEvent::_internal_participant_uuid() const {
  return participant_uuid_.Get();
}
inline void ParticipantEvent::_internal_set_participant_uuid(const std::string& value) {
  
  participant_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ParticipantEvent::_internal_mutable_participant_uuid() {
  
  return participant_uuid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ParticipantEvent::release_participant_uuid() {
  // @@protoc_insertion_point(field_release:opentera.protobuf.ParticipantEvent.participant_uuid)
  return participant_uuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ParticipantEvent::set_allocated_participant_uuid(std::string* participant_uuid) {
  if (participant_uuid != nullptr) {
    
  } else {
    
  }
  participant_uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), participant_uuid,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:opentera.protobuf.ParticipantEvent.participant_uuid)
}

// .opentera.protobuf.ParticipantEvent.EventType type = 2;
inline void ParticipantEvent::clear_type() {
  type_ = 0;
}
inline ::opentera::protobuf::ParticipantEvent_EventType ParticipantEvent::_internal_type() const {
  return static_cast< ::opentera::protobuf::ParticipantEvent_EventType >(type_);
}
inline ::opentera::protobuf::ParticipantEvent_EventType ParticipantEvent::type() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.ParticipantEvent.type)
  return _internal_type();
}
inline void ParticipantEvent::_internal_set_type(::opentera::protobuf::ParticipantEvent_EventType value) {
  
  type_ = value;
}
inline void ParticipantEvent::set_type(::opentera::protobuf::ParticipantEvent_EventType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:opentera.protobuf.ParticipantEvent.type)
}

// string participant_name = 3;
inline void ParticipantEvent::clear_participant_name() {
  participant_name_.ClearToEmpty();
}
inline const std::string& ParticipantEvent::participant_name() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.ParticipantEvent.participant_name)
  return _internal_participant_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ParticipantEvent::set_participant_name(ArgT0&& arg0, ArgT... args) {
 
 participant_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:opentera.protobuf.ParticipantEvent.participant_name)
}
inline std::string* ParticipantEvent::mutable_participant_name() {
  std::string* _s = _internal_mutable_participant_name();
  // @@protoc_insertion_point(field_mutable:opentera.protobuf.ParticipantEvent.participant_name)
  return _s;
}
inline const std::string& ParticipantEvent::_internal_participant_name() const {
  return participant_name_.Get();
}
inline void ParticipantEvent::_internal_set_participant_name(const std::string& value) {
  
  participant_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ParticipantEvent::_internal_mutable_participant_name() {
  
  return participant_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ParticipantEvent::release_participant_name() {
  // @@protoc_insertion_point(field_release:opentera.protobuf.ParticipantEvent.participant_name)
  return participant_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ParticipantEvent::set_allocated_participant_name(std::string* participant_name) {
  if (participant_name != nullptr) {
    
  } else {
    
  }
  participant_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), participant_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:opentera.protobuf.ParticipantEvent.participant_name)
}

// string participant_project_name = 4;
inline void ParticipantEvent::clear_participant_project_name() {
  participant_project_name_.ClearToEmpty();
}
inline const std::string& ParticipantEvent::participant_project_name() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.ParticipantEvent.participant_project_name)
  return _internal_participant_project_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ParticipantEvent::set_participant_project_name(ArgT0&& arg0, ArgT... args) {
 
 participant_project_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:opentera.protobuf.ParticipantEvent.participant_project_name)
}
inline std::string* ParticipantEvent::mutable_participant_project_name() {
  std::string* _s = _internal_mutable_participant_project_name();
  // @@protoc_insertion_point(field_mutable:opentera.protobuf.ParticipantEvent.participant_project_name)
  return _s;
}
inline const std::string& ParticipantEvent::_internal_participant_project_name() const {
  return participant_project_name_.Get();
}
inline void ParticipantEvent::_internal_set_participant_project_name(const std::string& value) {
  
  participant_project_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ParticipantEvent::_internal_mutable_participant_project_name() {
  
  return participant_project_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ParticipantEvent::release_participant_project_name() {
  // @@protoc_insertion_point(field_release:opentera.protobuf.ParticipantEvent.participant_project_name)
  return participant_project_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ParticipantEvent::set_allocated_participant_project_name(std::string* participant_project_name) {
  if (participant_project_name != nullptr) {
    
  } else {
    
  }
  participant_project_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), participant_project_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:opentera.protobuf.ParticipantEvent.participant_project_name)
}

// string participant_site_name = 5;
inline void ParticipantEvent::clear_participant_site_name() {
  participant_site_name_.ClearToEmpty();
}
inline const std::string& ParticipantEvent::participant_site_name() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.ParticipantEvent.participant_site_name)
  return _internal_participant_site_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ParticipantEvent::set_participant_site_name(ArgT0&& arg0, ArgT... args) {
 
 participant_site_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:opentera.protobuf.ParticipantEvent.participant_site_name)
}
inline std::string* ParticipantEvent::mutable_participant_site_name() {
  std::string* _s = _internal_mutable_participant_site_name();
  // @@protoc_insertion_point(field_mutable:opentera.protobuf.ParticipantEvent.participant_site_name)
  return _s;
}
inline const std::string& ParticipantEvent::_internal_participant_site_name() const {
  return participant_site_name_.Get();
}
inline void ParticipantEvent::_internal_set_participant_site_name(const std::string& value) {
  
  participant_site_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ParticipantEvent::_internal_mutable_participant_site_name() {
  
  return participant_site_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ParticipantEvent::release_participant_site_name() {
  // @@protoc_insertion_point(field_release:opentera.protobuf.ParticipantEvent.participant_site_name)
  return participant_site_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ParticipantEvent::set_allocated_participant_site_name(std::string* participant_site_name) {
  if (participant_site_name != nullptr) {
    
  } else {
    
  }
  participant_site_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), participant_site_name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:opentera.protobuf.ParticipantEvent.participant_site_name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace opentera

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::opentera::protobuf::ParticipantEvent_EventType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::opentera::protobuf::ParticipantEvent_EventType>() {
  return ::opentera::protobuf::ParticipantEvent_EventType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ParticipantEvent_2eproto
