// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StopSessionEvent.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_StopSessionEvent_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_StopSessionEvent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_StopSessionEvent_2eproto OPENTERAMESSAGES_EXPORT
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct OPENTERAMESSAGES_EXPORT TableStruct_StopSessionEvent_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
OPENTERAMESSAGES_EXPORT extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_StopSessionEvent_2eproto;
namespace opentera {
namespace protobuf {
class StopSessionEvent;
struct StopSessionEventDefaultTypeInternal;
OPENTERAMESSAGES_EXPORT extern StopSessionEventDefaultTypeInternal _StopSessionEvent_default_instance_;
}  // namespace protobuf
}  // namespace opentera
PROTOBUF_NAMESPACE_OPEN
template<> OPENTERAMESSAGES_EXPORT ::opentera::protobuf::StopSessionEvent* Arena::CreateMaybeMessage<::opentera::protobuf::StopSessionEvent>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace opentera {
namespace protobuf {

// ===================================================================

class OPENTERAMESSAGES_EXPORT StopSessionEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentera.protobuf.StopSessionEvent) */ {
 public:
  inline StopSessionEvent() : StopSessionEvent(nullptr) {}
  ~StopSessionEvent() override;
  explicit constexpr StopSessionEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StopSessionEvent(const StopSessionEvent& from);
  StopSessionEvent(StopSessionEvent&& from) noexcept
    : StopSessionEvent() {
    *this = ::std::move(from);
  }

  inline StopSessionEvent& operator=(const StopSessionEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopSessionEvent& operator=(StopSessionEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopSessionEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const StopSessionEvent* internal_default_instance() {
    return reinterpret_cast<const StopSessionEvent*>(
               &_StopSessionEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StopSessionEvent& a, StopSessionEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(StopSessionEvent* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopSessionEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StopSessionEvent* New() const final {
    return new StopSessionEvent();
  }

  StopSessionEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StopSessionEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StopSessionEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const StopSessionEvent& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StopSessionEvent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentera.protobuf.StopSessionEvent";
  }
  protected:
  explicit StopSessionEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionUuidFieldNumber = 1,
    kServiceUuidFieldNumber = 2,
  };
  // string session_uuid = 1;
  void clear_session_uuid();
  const std::string& session_uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_session_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_session_uuid();
  PROTOBUF_MUST_USE_RESULT std::string* release_session_uuid();
  void set_allocated_session_uuid(std::string* session_uuid);
  private:
  const std::string& _internal_session_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_session_uuid(const std::string& value);
  std::string* _internal_mutable_session_uuid();
  public:

  // string service_uuid = 2;
  void clear_service_uuid();
  const std::string& service_uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_service_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_service_uuid();
  PROTOBUF_MUST_USE_RESULT std::string* release_service_uuid();
  void set_allocated_service_uuid(std::string* service_uuid);
  private:
  const std::string& _internal_service_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_service_uuid(const std::string& value);
  std::string* _internal_mutable_service_uuid();
  public:

  // @@protoc_insertion_point(class_scope:opentera.protobuf.StopSessionEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_uuid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_uuid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_StopSessionEvent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StopSessionEvent

// string session_uuid = 1;
inline void StopSessionEvent::clear_session_uuid() {
  session_uuid_.ClearToEmpty();
}
inline const std::string& StopSessionEvent::session_uuid() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.StopSessionEvent.session_uuid)
  return _internal_session_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StopSessionEvent::set_session_uuid(ArgT0&& arg0, ArgT... args) {
 
 session_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:opentera.protobuf.StopSessionEvent.session_uuid)
}
inline std::string* StopSessionEvent::mutable_session_uuid() {
  std::string* _s = _internal_mutable_session_uuid();
  // @@protoc_insertion_point(field_mutable:opentera.protobuf.StopSessionEvent.session_uuid)
  return _s;
}
inline const std::string& StopSessionEvent::_internal_session_uuid() const {
  return session_uuid_.Get();
}
inline void StopSessionEvent::_internal_set_session_uuid(const std::string& value) {
  
  session_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* StopSessionEvent::_internal_mutable_session_uuid() {
  
  return session_uuid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* StopSessionEvent::release_session_uuid() {
  // @@protoc_insertion_point(field_release:opentera.protobuf.StopSessionEvent.session_uuid)
  return session_uuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void StopSessionEvent::set_allocated_session_uuid(std::string* session_uuid) {
  if (session_uuid != nullptr) {
    
  } else {
    
  }
  session_uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), session_uuid,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:opentera.protobuf.StopSessionEvent.session_uuid)
}

// string service_uuid = 2;
inline void StopSessionEvent::clear_service_uuid() {
  service_uuid_.ClearToEmpty();
}
inline const std::string& StopSessionEvent::service_uuid() const {
  // @@protoc_insertion_point(field_get:opentera.protobuf.StopSessionEvent.service_uuid)
  return _internal_service_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StopSessionEvent::set_service_uuid(ArgT0&& arg0, ArgT... args) {
 
 service_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:opentera.protobuf.StopSessionEvent.service_uuid)
}
inline std::string* StopSessionEvent::mutable_service_uuid() {
  std::string* _s = _internal_mutable_service_uuid();
  // @@protoc_insertion_point(field_mutable:opentera.protobuf.StopSessionEvent.service_uuid)
  return _s;
}
inline const std::string& StopSessionEvent::_internal_service_uuid() const {
  return service_uuid_.Get();
}
inline void StopSessionEvent::_internal_set_service_uuid(const std::string& value) {
  
  service_uuid_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* StopSessionEvent::_internal_mutable_service_uuid() {
  
  return service_uuid_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* StopSessionEvent::release_service_uuid() {
  // @@protoc_insertion_point(field_release:opentera.protobuf.StopSessionEvent.service_uuid)
  return service_uuid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void StopSessionEvent::set_allocated_service_uuid(std::string* service_uuid) {
  if (service_uuid != nullptr) {
    
  } else {
    
  }
  service_uuid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), service_uuid,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:opentera.protobuf.StopSessionEvent.service_uuid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace opentera

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_StopSessionEvent_2eproto
