name: gen-doc-and-deploy-to-github-pages

on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.4]

    steps:
    - name: Generate base documentation
      working-directory: docs
      run: |
        pip install -r requirements.txt
        make html
        touch _build/html/.nojekyll
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: docs/_build/html

